version: '3'
services:
  postgres-db:
    image: postgres:12.4-alpine
    restart: always
    environment:
        POSTGRES_USER: teste
        POSTGRES_PASSWORD: teste
        POSTGRES_DB: captacao
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432